<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      /*
            1.  如何改变promise的状态？
              (1)resolve(value):如果当前是pending就会变为resolved
              (2)reject(reason):如果当前是pending就会变为rejected
              (3)抛出异常：如果当前是pending就会变为rejected(容易忽略)
          */

      // const p = new Promise((resolve, reject) => {
      //   //  resolve(1)//promise变为resolved状态
      //   //  reject(2) //promise变为rejected状态
      //   //  throw new Error('错了') //抛出异常，promise变为rejected状态，reason就是就是抛出的error
      //   // 也可以这样
      //   throw 3; //抛出异常，promise变为rejected失败状态，reason就是3
      // });
      // p.catch((reason) => {
      //   console.log(reason);
      // });

       /*
             2.  一个promise指定多个成功/失败的回调函数，都会调用吗？
                当promise改变对应的状态时 都会 调用
         */
      //指定多个回调函数

      // p.then(
      //   () => {},
      //   (reason) => {
      //     console.log("reason2", reason);
      //   }
      // );

      // p.then(
      //   () => {},
      //   (reason) => {
      //     console.log("reason3", reason);
      //   }
      // );

      /*
            3. 改变promise状态和指定回调函数谁先谁后？
              (1)都有可能，正常情况下都是先指定回调函数再改变状态，但也可以先改变状态在指定回调函数
              (2)如何先改变状态再指定回调？
                ① 在执行器中直接调用resolve()/reject()
                ② 延时更长的时间才调用then
              (3)什么时候才能得到数据
                ① 如果先指定得回调，那么当状态改变的时，回调函数就会调用，得到数据
                ② 如果先改变的状态，那当指定回调时，回调函数就会调用，得到数据
         */

      /*
          4. promise.then()返回的新promise的结果状态由什么决定？
            (1)简单表达：由then()指定的回调函数执行的结果决定
            (2)详细表述：
                    ① 如果抛出异常，新的promise变为rejected，reason为抛出的异常
                    ② 如果返回的时非promise的任意值，新promise变为resolved，value为返回的值
                    ③ 如果返回的是另一个新的promise，此promise的结果就会成为新的promise结果
        */

      // new Promise((resolve, reject) => {
      //   resolve(1);
      // })
      //   .then(
      //     (value) => {
      //       console.log("onResolved1", value);
      //       // return 2;        //② 如果返回的时非promise的任意值，新promise变为resolved，value为返回的值
      //       // return Promise.resolve(2); // ③ 如果返回的是另一个新的promise，此promise的结果就会成为新的promise结果
      //       return Promise.reject(4); // ③ 如果返回的是另一个新的promise，此promise的结果就会成为新的promise结果
      //       // throw 5;           //抛出异常，新的promise变为rejected，reason为抛出的异常
      //     },
      //     (reason) => {
      //       console.log("onResolved1", reason);
      //     }
      //   )
      //   .then(
      //     (value) => {
      //       console.log("onResolved2", value);
      //     },
      //     (reason) => {
      //       console.log("onRejected", reason);
      //     }
      //   );
      // /*
      //           5.promise如何串联多个操作任务
      //             (1)promise的then()返回一个新的promise,可以看成then()的链式调用
      //             (2)通过then()的链式调用串联多个同步/异步任务
      //       */
      // new Promise((resolve, rejecte) => {
      //   setTimeout(() => {
      //     console.log("执行任务1(异步)");
      //     resolve(1);
      //   }, 1000);
      // })
      //   .then((value) => {
      //     console.log("任务一的结果：", value);
      //     console.log("执行任务2(同步)");
      //     return 2;
      //   })
      //   .then((value) => {
      //     console.log("任务2的结果", value);
      //     //启动一个任务3(异步)
      //     return new Promise((resolve) => {
      //       //这里串一个异步的，用promise封装异步操作。如果这里直接写resolve(3)，
      //       //此时这个resolve属于93行的promise的，只能由excutor执行器函数使用的
      //       setTimeout(() => {
      //         console.log("执行任务3(异步)");
      //         resolve(3);
      //       }, 1000);
      //     });
      //   })
      //   .then((value) => {
      //     console.log("任务3的结果：", value);
      //   });


      /* 
              6.promise异常传透?
                (1)当使用promise的then链式调用时，可以在最后指定失败的回调
                (2)当前面任何操作除了异常，都会传到最后失败的回调中处理
      
           */

      // new Promise((resolve, reject) => {
      //   reject(1); //这里发生异常 ，通过层层传透直到最后的catch来处理.
      //   //在137，143，149相当于有一个抛异常的回调函数 或者 Promise.reject(reason)
      // })
      //   .then(
      //     (value) => {
      //       console.log(value);
      //     }
      //     //,(reason) => {throw reason}
      //   )
      //   .then(
      //     (value) => {
      //       console.log(value);
      //     }
      //     //,(reason) => {throw reason}
      //   )
      //   .then(
      //     (value) => {
      //       console.log(value);
      //     }
      //     //,(reason) => {throw reason}
      //   )
      //   .catch((reason) => {
      //     console.log("异常传透", reason);
      //   });

      /* 
        7.中断promise链?
                (1)当使用promise的then链式调用时，在中间中断，不在调用后面的回调函数
                (2)办法：在回调函数中返回一个pending状态的promise对象 
      */
      new Promise((resolve, reject) => {
        reject(1);
      })
        .then((value) => {
          console.log(value);
        })
        .then((value) => {
          console.log(value);
        })
        .then(
          (value) => {
            console.log(value);
          })
        .catch(//这里的catch也返回一个新promise
          (reason) => {
            console.log(reason);
            return new Promise(() => {}); //这里返回一个什么内容都不写的，相当于返回了一个pending状态的promise.此时中断promise链
          }
        )
        .then(
          (value) => {
            console.log("onResolved", value);
          },
          (reason) => {
            console.log("onRejected", reason);
          }
        );
        
    </script>
  </body>
</html>
